services:
  - type: web
    name: horse-colic-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
